In [2]:
import requests
import xmltodict
from datetime import datetime
import pandas as pd
from scipy import stats
import matplotlib.pyplot as plt
import pprint
import ast
import json
from io import StringIO
pp = pprint.PrettyPrinter(indent=2)

In [71]:
passing_base_url = "https://premium.pff.com/api/v1/facet/passing/summary?league=nfl&season=2020&export=true"
passing_df = pd.DataFrame()
for i in range(1, 17):
    url = f"{passing_base_url}&week={i}"
    r = requests.get(url)
    print(r)
    week_stats = pd.read_csv(StringIO(r.text)).dropna(axis=1, how="all")
    week_stats["week"] = i
    passing_df = passing_df.append(week_stats, ignore_index=True)

<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>

In [116]:
passing_df = passing_df.drop(columns="player_game_count").rename(columns={"attempts": "passing_attempts",
                                                             "yards": "passing_yards",
                                                             "touchdowns": "passing_touchdowns",
                                                             "ypa": "passing_ypa"})

In [73]:
receiving_base_url = "https://premium.pff.com/api/v1/facet/receiving/summary?league=nfl&season=2020&export=true"
receiving_df = pd.DataFrame()
for i in range(1, 17):
    url = f"{receiving_base_url}&week={i}"
    r = requests.get(url)
    print(r)
    week_stats = pd.read_csv(StringIO(r.text)).dropna(axis=1, how="all")
    week_stats["week"] = i
    receiving_df = receiving_df.append(week_stats, ignore_index=True)

<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>

In [118]:
receiving_df = receiving_df.drop(columns="player_game_count").rename(columns={"yards": "receiving_yards",
                                                                              "touchdowns": "receiving_touchdowns"})

In [97]:
rushing_base_url = "https://premium.pff.com/api/v1/facet/rushing/summary?league=nfl&season=2020&export=true"
rushing_df = pd.DataFrame()
for i in range(1, 17):
    url = f"{rushing_base_url}&week={i}"
    r = requests.get(url)
    print(r)
    week_stats = pd.read_csv(StringIO(r.text)).dropna(axis=1, how="all")
    week_stats["week"] = i
    rushing_df = rushing_df.append(week_stats, ignore_index=True)

<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>

In [120]:
rushing_df = rushing_df.drop(columns="player_game_count").rename(columns={"attempts": "rushing_attempts",
                                                             "yards": "rushing_yards",
                                                             "touchdowns": "rushing_touchdowns",
                                                             "ypa": "rushing_ypa"})

In [96]:
field_goal_base_url = "https://premium.pff.com/api/v1/facet/field_goal/summary?league=nfl&season=2020&export=true"
field_goal_df = pd.DataFrame()
for i in range(1, 17):
    url = f"{field_goal_base_url}&week={i}"
    r = requests.get(url)
    print(r)
    week_stats = pd.read_csv(StringIO(r.text)).dropna(axis=1, how="all")
    week_stats["week"] = i
    field_goal_df = field_goal_df.append(week_stats, ignore_index=True)

<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>

In [123]:
field_goal_df = field_goal_df.drop(columns="player_game_count").

SyntaxError: invalid syntax (<ipython-input-123-0dc062dc530e>, line 1)

In [126]:
merged_df = passing_df.merge(rushing_df,
                             how="outer",
                             on=["player", "player_id", "position","team_name", "week"])

In [91]:
rushing_df.loc[(rushing_df["position"] == "HB") | (rushing_df["position"] == "FB"), "position"] = "RB"

In [99]:
passing_df[passing_df["position"] == "WR"]

,player,player_id,position,player_game_count,team_name,attempts,completions,completion_percent,yards,ypa,touchdowns,interceptions,qb_rating,week
68,Russell Gage,44771,WR,1,ATL,1,0,0.0,0,0.0,0,0,39.6,2
140,Jarvis Landry,8698,WR,1,CLV,1,1,100.0,37,37.0,1,0,158.3,4
175,Odell Beckham Jr.,8647,WR,1,CLV,1,1,100.0,18,18.0,0,0,118.8,5
177,Cedrick Wilson,48170,WR,1,DAL,1,1,100.0,11,11.0,1,0,152.1,5
207,Julian Edelman,5156,WR,1,NE,2,2,100.0,38,19.0,0,0,118.8,6
211,Randall Cobb,6216,WR,1,HST,1,0,0.0,0,0.0,0,0,39.6,6
243,Jarvis Landry,8698,WR,1,CLV,1,1,100.0,19,19.0,0,0,118.8,7
245,Tyler Boyd,10689,WR,1,CIN,1,1,100.0,16,16.0,0,0,118.8,7
280,Zach Pascal,12303,WR,1,IND,1,0,0.0,0,0.0,0,0,39.6,8
281,Golden Tate,5585,WR,1,NYG,1,1,100.0,18,18.0,0,0,118.8,8
282,Keenan Allen,7857,WR,1,LAC,1,0,0.0,0,0.0,0,0,39.6,8
350,Isaiah McKenzie,11927,WR,1,BUF,1,1,100.0,12,12.0,1,0,156.3,10
351,Jakobi Meyers,47468,WR,1,NE,1,1,100.0,24,24.0,1,0,158.3,10
384,D.J. Moore,48267,WR,1,CAR,1,0,0.0,0,0.0,0,0,39.6,11
423,Cole Beasley,7330,WR,1,BUF,1,1,100.0,20,20.0,1,0,158.3,12
426,Jamal Agnew,11920,WR,1,DET,1,0,0.0,0,0.0,0,0,39.6,12
427,Golden Tate,5585,WR,1,NYG,1,0,0.0,0,0.0,0,0,39.6,12
461,Jarvis Landry,8698,WR,1,CLV,1,1,100.0,6,6.0,0,0,91.7,13
462,Tyler Boyd,10689,WR,1,CIN,1,0,0.0,0,0.0,0,0,39.6,13
503,Zay Jones,11792,WR,1,LV,1,1,100.0,29,29.0,0,0,118.8,14
504,Russell Gage,44771,WR,1,ATL,1,1,100.0,39,39.0,1,0,158.3,14
505,Jarvis Landry,8698,WR,1,CLV,1,1,100.0,12,12.0,0,0,116.7,14
506,Isaiah Wright,40113,WR,1,WAS,1,0,0.0,0,0.0,0,0,39.6,14
507,Lynn Bowden Jr.,61361,WR,1,MIA,1,0,0.0,0,0.0,0,0,39.6,14
546,Cedrick Wilson,48170,WR,1,DAL,1,1,100.0,12,12.0,0,0,116.7,15
589,Jamison Crowder,9538,WR,1,NYJ,1,1,100.0,43,43.0,1,0,158.3,16
591,Sammy Watkins,8639,WR,1,KC,1,0,0.0,0,0.0,0,1,0.0,16
593,Alex Erickson,11107,WR,1,CIN,1,0,0.0,0,0.0,0,0,39.6,16

In [129]:
merged_df[merged_df["player_id"] == 8698]

,player,player_id,position,team_name,passing_attempts,completions,completion_percent,passing_yards,passing_ypa,passing_touchdowns,interceptions,qb_rating,week,rushing_attempts,rushing_yards,rushing_ypa,rushing_touchdowns,longest,fumbles
140,Jarvis Landry,8698,WR,CLV,1.0,1.0,100.0,37.0,37.0,1.0,0.0,158.3,4,NaN,NaN,NaN,NaN,NaN,NaN
243,Jarvis Landry,8698,WR,CLV,1.0,1.0,100.0,19.0,19.0,0.0,0.0,118.8,7,2.0,4.0,2.0,0.0,5.0,0.0
461,Jarvis Landry,8698,WR,CLV,1.0,1.0,100.0,6.0,6.0,0.0,0.0,91.7,13,NaN,NaN,NaN,NaN,NaN,NaN
505,Jarvis Landry,8698,WR,CLV,1.0,1.0,100.0,12.0,12.0,0.0,0.0,116.7,14,NaN,NaN,NaN,NaN,NaN,NaN
1636,Jarvis Landry,8698,WR,CLV,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11,1.0,3.0,3.0,0.0,3.0,0.0

In [134]:
rushing_df[rushing_df["position"] == "CB"]

,player,player_id,position,team_name,rushing_attempts,rushing_yards,rushing_ypa,rushing_touchdowns,longest,fumbles,week
864,Myles Hartsfield,49159,CB,CAR,2,2,1.0,0,2,0,7

In [135]:
defense_base_url = "https://premium.pff.com/api/v1/facet/defense/summary?league=nfl&season=2020&export=true"
defense_df = pd.DataFrame()
for i in range(1, 17):
    url = f"{defense_base_url}&week={i}"
    r = requests.get(url)
    print(r)
    week_stats = pd.read_csv(StringIO(r.text)).dropna(axis=1, how="all")
    week_stats["week"] = i
    defense_df = defense_df.append(week_stats, ignore_index=True)

<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>

In [137]:
defense_df[defense_df["player"] == "Troy Hill"]

,player,player_id,position,player_game_count,team_name,sacks,hits,tackles,assists,forced_fumbles,interceptions,pass_break_ups,week
194,Troy Hill,9881,CB,1,LA,0.0,0.0,5.0,0.0,0.0,0.0,0.0,1
817,Troy Hill,9881,CB,1,LA,0.0,0.0,8.0,0.0,0.0,1.0,0.0,2
1435,Troy Hill,9881,CB,1,LA,0.0,0.0,6.0,1.0,0.0,0.0,0.0,3
2024,Troy Hill,9881,CB,1,LA,0.0,0.0,6.0,0.0,0.0,0.0,2.0,4
2599,Troy Hill,9881,CB,1,LA,0.0,0.0,0.0,1.0,0.0,0.0,0.0,5
3134,Troy Hill,9881,CB,1,LA,0.0,0.0,6.0,1.0,0.0,0.0,1.0,6
3674,Troy Hill,9881,CB,1,LA,0.0,0.0,5.0,2.0,0.0,0.0,1.0,7
4209,Troy Hill,9881,CB,1,LA,0.0,0.0,5.0,0.0,0.0,0.0,0.0,8
5300,Troy Hill,9881,CB,1,LA,0.0,0.0,2.0,1.0,0.0,0.0,0.0,10
5858,Troy Hill,9881,CB,1,LA,0.0,0.0,6.0,0.0,0.0,0.0,0.0,11
6446,Troy Hill,9881,CB,1,LA,0.0,0.0,6.0,0.0,1.0,0.0,0.0,12
7061,Troy Hill,9881,CB,1,LA,0.0,0.0,4.0,1.0,0.0,1.0,1.0,13
7640,Troy Hill,9881,CB,1,LA,0.0,0.0,1.0,0.0,0.0,0.0,1.0,14
8260,Troy Hill,9881,CB,1,LA,0.0,0.0,1.0,1.0,0.0,0.0,0.0,15
8886,Troy Hill,9881,CB,1,LA,0.0,0.0,0.0,2.0,0.0,0.0,0.0,16

In [3]:
passing_base_url = "https://www.pff.com/api/fantasy/stats/passing?season=2020"
r = requests.get(passing_json_url)
json_data = pd.read_json(StringIO(r.text))

passing_df = pd.DataFrame()
for i in range(1, 17):
    url = f"{passing_base_url}&week={i}"
    r = requests.get(url)
    print(r)
    week_stats = pd.read_json(StringIO(r.text))
    week_stats["week"] = i
    defense_df = defense_df.append(week_stats, ignore_index=True)

In [4]:
json_data

,att,comp,dropbacks,fumbles,games,ints,player,player_id,rush_carries,rush_tds,rush_yds,tds,team,team_id,yds
0,46,33,53,2,1,0,Josh Allen,46601,15,1,57,2,BUF,4,312
1,39,21,42,0,1,1,Baker Mayfield,46518,2,0,3,1,CLV,8,189
2,0,0,0,0,1,0,Chris Streveler,46440,1,0,3,0,ARZ,1,0
3,25,20,29,1,1,0,Lamar Jackson,46416,7,0,45,3,BLT,3,275
4,31,17,36,1,1,0,Dwayne Haskins,41897,7,0,17,1,WAS,32,178
5,20,19,28,0,1,0,Gardner Minshew,41401,5,0,19,3,JAX,15,173
6,33,22,34,2,1,0,Drew Lock,39517,3,0,5,1,DEN,10,216
7,41,26,48,0,1,2,Daniel Jones,39395,4,0,22,2,NYG,21,279
8,40,26,51,0,1,1,Kyler Murray,38334,13,1,91,1,ARZ,1,230
9,35,21,39,0,1,1,Sam Darnold,29048,1,0,6,1,NYJ,22,215
10,36,23,44,1,1,1,Joe Burrow,28022,8,1,46,0,CIN,7,193
11,0,0,0,0,1,0,Tim Boyle,21956,2,0,-2,0,GB,12,0
12,1,1,2,0,1,0,Taysom Hill,12112,3,0,13,0,NO,20,38
13,32,20,40,0,1,1,Deshaun Watson,11767,6,1,27,1,HST,13,253
14,32,24,33,0,1,0,Patrick Mahomes,11765,0,0,0,3,KC,16,211
15,36,20,40,1,1,0,Mitchell Trubisky,11757,3,0,26,3,CHI,6,242
16,39,25,45,0,1,0,Dak Prescott,10769,3,0,30,1,DAL,9,266
17,0,0,1,0,1,0,Jacoby Brissett,10725,0,0,0,0,IND,14,0
18,42,24,50,2,1,2,Carson Wentz,10636,1,0,2,2,PHI,24,270
19,31,20,34,0,1,1,Jared Goff,10635,4,0,15,0,LA,26,275
20,33,19,37,0,1,0,Jimmy Garoppolo,8697,1,0,9,2,SF,28,259
21,30,22,30,0,1,0,Derek Carr,8671,0,0,0,1,LV,23,239
22,34,22,39,0,1,0,Teddy Bridgewater,8667,4,0,26,1,CAR,5,269
23,25,19,31,0,1,1,Kirk Cousins,7102,4,0,34,2,MIN,18,259
24,35,31,39,1,1,0,Russell Wilson,7077,3,0,29,4,SEA,29,322
25,43,29,45,0,1,0,Ryan Tannehill,7014,3,0,14,2,TEN,31,249
26,1,1,1,0,1,0,Robert Griffin III,7008,1,0,-1,0,BLT,3,9
27,30,16,34,0,1,0,Tyrod Taylor,6332,7,0,6,0,LAC,27,208
28,19,15,22,0,1,0,Cam Newton,6153,15,2,75,0,NE,19,155
29,42,24,47,0,1,1,Matthew Stafford,4924,5,0,23,1,DET,11,297
30,54,37,56,0,1,1,Matt Ryan,4317,1,0,-1,2,ATL,2,450
31,30,20,34,1,1,3,Ryan Fitzpatrick,2467,5,0,18,0,MIA,17,191
32,44,32,44,0,1,0,Aaron Rodgers,2241,1,0,2,4,GB,12,364
33,32,21,36,2,1,0,Ben Roethlisberger,1732,3,0,9,3,PIT,25,229
34,46,36,47,0,1,2,Philip Rivers,1725,1,0,3,1,IND,14,363
35,30,18,32,0,1,0,Drew Brees,802,2,0,0,2,NO,20,160
36,36,23,41,1,1,2,Tom Brady,698,3,1,9,2,TB,30,239